name: nf-core-denovohybrid-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - bandage=0.8.1
  - bcftools=1.8
  - biopython=1.73
  - blas=1.0
  - blast=2.5.0
  - boost=1.67.0
  - bowtie2=2.3.4.1
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - circos=0.69.8
  - click=7.0
  - colormath=3.0.0
  - cryptography=2.7
  - curl=7.65.2
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - fastqc=0.11.8
  - filtlong=0.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.0
  - freebayes=0.9.21.7
  - freetype=2.9.1
  - future=0.17.1
  - giflib=5.1.4
  - glib=2.56.2
  - glimmerhmm=3.0.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - htslib=1.9
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipython_genutils=0.2.0
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.65.2
  - libdeflate=1.2
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgd=2.2.5
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libwebp=1.0.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lzstring=1.0.4
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - miniasm=0.3_r179
  - minimap2=2.17
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - multiqc=1.7
  - nanoget=1.8.0
  - nanomath=0.23.1
  - nanoplot=1.26.2
  - nanoplotter=1.8.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - ngs-bits=2019_04
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openjdk=8.0.152
  - openssl=1.1.1c
  - pandas=0.24.2
  - patsy=0.5.1
  - pauvre=0.1.86
  - pcre=8.43
  - perl=5.26.2
  - perl-autoloader=5.74
  - perl-carp=1.38
  - perl-clone=0.41
  - perl-config-general=2.63
  - perl-digest-perl-md5=1.9
  - perl-dynaloader=1.25
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-font-ttf=1.06
  - perl-gd=2.71
  - perl-io-string=1.08
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-math-bezier=0.01
  - perl-math-round=0.07
  - perl-math-vecstat=0.08
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-number-format=1.75
  - perl-params-validate=1.29
  - perl-pathtools=3.75
  - perl-readonly=2.05
  - perl-regexp-common=2017060201
  - perl-scalar-list-utils=1.50
  - perl-set-intspan=1.19
  - perl-statistics-basic=1.6611
  - perl-svg=2.84
  - perl-text-format=0.59
  - perl-time-hires=1.9760
  - perl-try-tiny=0.30
  - perl-xml-parser=2.44
  - perl-xsloader=0.24
  - pilon=1.23
  - pip=19.1.1
  - plotly=3.10.0
  - porechop=0.2.3_seqan2.1.1
  - py-boost=1.67.0
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysam=0.11.2.2
  - pysocks=1.7.0
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1.1
  - qt=5.9.7
  - quast=5.0.2
  - r=3.5.0
  - r-markdown=0.8
  - racon=1.4.0
  - readline=7.0
  - requests=2.22.0
  - retrying=1.3.3
  - samtools=1.6
  - scipy=1.2.1
  - seaborn=0.9.0
  - seqtk=1.3
  - setuptools=41.0.1
  - simplejson=3.8.1
  - sip=4.19.8
  - six=1.12.0
  - spades=3.13.1
  - spectra=0.0.11
  - sqlite=3.29.0
  - statsmodels=0.10.0
  - tbb=2019.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2
  - unicycler=0.4.7
  - urllib3=1.25.3
  - wheel=0.33.4
  - wtdbg=2.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
