name: nf-core-denovohybrid-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - pkgs/main
dependencies:
  - bandage=0.8.1
  - bcftools=1.8
  - fastqc=0.11.8
  - filtlong=0.2.0
  - nanoplot=1.26.2
  - ngs-bits=2019_04
  - quast=5.0.2
  - r=3.5.0
  - r-markdown=0.8
  - seqtk=1.3
  - unicycler=0.4.7
  - wtdbg=2.3
